---
- name: RabbitMQ | Add Erlang signing key
  apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: RabbitMQ | Add Erlang Solutions repository
  apt_repository:
    repo: '{{ ubuntu_erlang_repo }}'
    state: present
    
- name: RabbitMQ | Update cache
  apt:
    update_cache: yes

- name: RabbitMQ | Install erlang
  apt:
    name: erlang
    state: present
    
- name: RabbitMQ | Install SoCat
  apt: 
    name: socat
    state: present