---
- name: RabbitMQ | setting up ha on queue(s)
  rabbitmq_policy:
      name: 'ha-all'
      pattern: '.*'
      vhost: '{{ vhost_name }}'
      tags:
          ha-mode: all
          ha-sync-mode: automatic
      state: present
  run_once: true
