---
- name: Percona | Import Percona Repo
  yum:
      name: "{{ percona_repo_url }}"
      state: present

- name: Percona | Install Percona
  yum: 
      name: "{{ percona_db_version }}"
      state: present

- name: Percona | Ensuring the Percona Service is running
  systemd: 
      name: mysql
      state: started
      enabled: true