---
- name: Elasticsearch | Install Elasticsearch
  apt:
      deb: "{{ ubuntu_elasticsearch_package }}"
      state: present

- name: Elasticsearch | Ensuring the Elasticsearch Service is running
  systemd:
    name: elasticsearch
    state: started
    enabled: yes 