---
- include_tasks: java.yml

- include_tasks: elasticsearch_install.yml

- include_tasks: elasticsearch_config.yml

- name: Elasticsearch | restart Elasticsearch
  service:
      name: elasticsearch
      state: restarted